type DirectoryPath = string;
type FileName = string;
type FilePath = string;
type Milliseconds = number;
export type FileCacheOptions<T extends Record<string, any>> = {
    cachePath: DirectoryPath;
    autoCreateCachePath?: boolean;
    cb: (filePath: FilePath, args: T, cache: FileCache<T>) => Promise<void>;
    ext: (args: T) => string | Promise<string>;
    resolveCacheKey?: (args: T) => string | Promise<string>;
    ttl: Milliseconds;
    cleanupInterval?: Milliseconds;
};
declare class FileCache<T extends Record<string, any>> {
    private _cachePath;
    private _cb;
    private _ttl;
    private _cleanupInterval;
    private _resolveCacheKey;
    private _ext;
    private _intervalId;
    private _semaphore;
    private _cleanupGroupSemaphore;
    constructor({ cachePath, autoCreateCachePath, cb, ext, ttl, cleanupInterval, resolveCacheKey, }: FileCacheOptions<T>);
    /**
     * Resolves the filename for the cache based on the provided arguments.
     *
     * Uses the provided `resolveFileName` function if available, or falls back to
     * generating a hash from the arguments to create a unique file name.
     */
    private resolveFileName;
    /**
     * Retrieves a cached file for the given arguments.
     * If the file doesn't exist, it is generated by the callback and stored.
     *
     * Concurrency-safe, ensuring no conflicts when multiple requests are made
     * for the same file.
     *
     * @param args The arguments used to determine the file's identity and generation
     * @returns The path to the cached or newly created file
     */
    getFile(args: T): Promise<FilePath>;
    /**
     * Resolves the full file path for the cached file based on the provided arguments.
     *
     * @param args The arguments used to resolve the file path
     * @returns The full path to the cached file
     */
    resolveFilePath(args: T): Promise<FilePath>;
    /**
     * Stops the background cleanup process, but does not delete any cached files.
     */
    destroy(): void;
    has(args: T): Promise<boolean>;
    /**
     * Runs a cleanup pass to remove files older than 1 day from the cache.
     * This is called periodically, but can be triggered manually.
     */
    cleanup(): Promise<void>;
}
export { type DirectoryPath, FileCache, type FileName, type FilePath };
